server:
  port: 8090

spring:
  profiles:
    active: "CA"

logging.level.org.springframework.security: trace

---
spring:
  profiles: keycloak

logging.level.org.keycloak: trace

keycloak:
  enable-basic-auth: false
  realm: SpringBoot
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: product-service
  use-resource-role-mappings: true
  public-client: false
  bearer-only: true
  securityConstraints:
  -   authRoles:
      - user
      securityCollections:
      -   name: A Simple Message test
          patterns:
          - /message

---
spring:
  profiles: CA
  autoconfigure:
      exclude: org.keycloak.adapters.springboot.KeycloakAutoConfiguration

oauth:
  clientId: 2b0a60f4-3e96-4fdd-97e7-36192b35b3f1
  clientSecret: 522a7aec-e5f4-423b-94af-09410a8bcc53
  accessTokenUri: https://localhost:8443/auth/oauth/v2/token
  grantType: client_credentials
  scope: read
