server:
  port: 8090

spring:
  profiles:
    active: "CA"

logging.level.org.springframework.security: trace

---
spring:
  profiles: keycloak

logging.level.org.keycloak: trace

keycloak:
  enable-basic-auth: false
  realm: SpringBoot
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: product-service
  use-resource-role-mappings: true
  public-client: false
  bearer-only: true
  securityConstraints:
  -   authRoles:
      - user
      securityCollections:
      -   name: A Simple Message test
          patterns:
          - /message

---
spring:
  profiles: CA
  autoconfigure:
      exclude: org.keycloak.adapters.springboot.KeycloakAutoConfiguration

oauth:
  clientId: ea60d2a7-0f8c-452b-9c6e-cdef86ce2d7c
  clientSecret: 871a154f-8ba5-4b48-9ca0-5f19c07ba389
  accessTokenUri: https://localhost:8443/auth/oauth/v2/token
  grantType: client_credentials
  scope: read
