server:
  port: 8090

spring:
  profiles:
    active: "CA"

logging.level.org.springframework.security: trace

---
spring:
  profiles: keycloak

logging.level.org.keycloak: trace

keycloak:
  enable-basic-auth: false
  realm: SpringBoot
  auth-server-url: http://localhost:8180/auth
  ssl-required: external
  resource: product-service
  use-resource-role-mappings: true
  public-client: false
  bearer-only: true
  securityConstraints:
  -   authRoles:
      - user
      securityCollections:
      -   name: A Simple Message test
          patterns:
          - /message

---
spring:
  profiles: CA
  autoconfigure:
      exclude: org.keycloak.adapters.springboot.KeycloakAutoConfiguration

oauth:
  clientId: 323ae95f-6bdc-4617-8613-bc86e255a3b1
  clientSecret: 9014b72f-f8d1-4e8b-9db9-877e56f5ab9f
  accessTokenUri: https://localhost:8443/auth/oauth/v2/token
  grantType: client_credentials
  scope: read
